# Generated by Django 5.2.1 on 2025-05-15 03:35

import django.db.models.deletion
import finance.models
import team.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfQuantityItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillOfQuantityItemDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_number', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('unit_type', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('ton', 'Ton'), ('lb', 'Pound'), ('m3', 'Cubic Meter'), ('l', 'Litre'), ('ml', 'Millilitre'), ('gal', 'Gallon'), ('ft3', 'Cubic Feet'), ('m', 'Meter'), ('cm', 'Centimeter'), ('mm', 'Millimeter'), ('in', 'Inch'), ('ft', 'Foot'), ('m2', 'Square Meter'), ('ft2', 'Square Feet'), ('unit', 'Unit'), ('pcs', 'Piece'), ('set', 'Set'), ('box', 'Box'), ('roll', 'Roll'), ('pack', 'Pack'), ('sheet', 'Sheet'), ('bag', 'Bag'), ('sack', 'Sack'), ('drum', 'Drum'), ('bundle', 'Bundle'), ('pallet', 'Pallet'), ('tube', 'Tube'), ('bottle', 'Bottle'), ('can', 'Can'), ('carton', 'Carton'), ('tray', 'Tray'), ('roller', 'Roller'), ('month', 'Month'), ('ls', 'Lump Sum')], default='g', max_length=20)),
                ('unit_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('work_weight', models.FloatField()),
                ('notes', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('labor', 'Labor'), ('equipment', 'Equipment'), ('miscellaneous', 'Miscellaneous'), ('travel', 'Travel'), ('subcontractor', 'Subcontractor'), ('overhead', 'Overhead'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('ton', 'Ton'), ('lb', 'Pound'), ('m3', 'Cubic Meter'), ('l', 'Litre'), ('ml', 'Millilitre'), ('gal', 'Gallon'), ('ft3', 'Cubic Feet'), ('m', 'Meter'), ('cm', 'Centimeter'), ('mm', 'Millimeter'), ('in', 'Inch'), ('ft', 'Foot'), ('m2', 'Square Meter'), ('ft2', 'Square Feet'), ('unit', 'Unit'), ('pcs', 'Piece'), ('set', 'Set'), ('box', 'Box'), ('roll', 'Roll'), ('pack', 'Pack'), ('sheet', 'Sheet'), ('bag', 'Bag'), ('sack', 'Sack'), ('drum', 'Drum'), ('bundle', 'Bundle'), ('pallet', 'Pallet'), ('tube', 'Tube'), ('bottle', 'Bottle'), ('can', 'Can'), ('carton', 'Carton'), ('tray', 'Tray'), ('roller', 'Roller'), ('month', 'Month'), ('ls', 'Lump Sum')], max_length=20)),
                ('subtotal', models.FloatField()),
                ('discount', models.FloatField(default=0.0)),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=20, null=True)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('total', models.FloatField()),
                ('notes', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseForMaterial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('labor', 'Labor'), ('equipment', 'Equipment'), ('miscellaneous', 'Miscellaneous'), ('travel', 'Travel'), ('subcontractor', 'Subcontractor'), ('overhead', 'Overhead'), ('other', 'Other')], max_length=20)),
                ('quantity', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('ton', 'Ton'), ('lb', 'Pound'), ('m3', 'Cubic Meter'), ('l', 'Litre'), ('ml', 'Millilitre'), ('gal', 'Gallon'), ('ft3', 'Cubic Feet'), ('m', 'Meter'), ('cm', 'Centimeter'), ('mm', 'Millimeter'), ('in', 'Inch'), ('ft', 'Foot'), ('m2', 'Square Meter'), ('ft2', 'Square Feet'), ('unit', 'Unit'), ('pcs', 'Piece'), ('set', 'Set'), ('box', 'Box'), ('roll', 'Roll'), ('pack', 'Pack'), ('sheet', 'Sheet'), ('bag', 'Bag'), ('sack', 'Sack'), ('drum', 'Drum'), ('bundle', 'Bundle'), ('pallet', 'Pallet'), ('tube', 'Tube'), ('bottle', 'Bottle'), ('can', 'Can'), ('carton', 'Carton'), ('tray', 'Tray'), ('roller', 'Roller'), ('month', 'Month'), ('ls', 'Lump Sum')], max_length=20)),
                ('subtotal', models.FloatField()),
                ('discount', models.FloatField(default=0.0)),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=20, null=True)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('total', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseOnProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total', models.FloatField()),
                ('notes', models.TextField()),
                ('photo_proof', models.ImageField(upload_to=finance.models.upload_expense_proof)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_from', models.CharField(max_length=255)),
                ('total', models.FloatField()),
                ('category', models.CharField(choices=[('down_payment', 'Down Payment'), ('progress_payment', 'Progress Payment'), ('final_payment', 'Final Payment'), ('other', 'Other')], max_length=20)),
                ('payment_date', models.DateField()),
                ('notes', models.TextField()),
                ('payment_proof', models.ImageField(upload_to=finance.models.upload_income_proof)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomeDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('ton', 'Ton'), ('lb', 'Pound'), ('m3', 'Cubic Meter'), ('l', 'Litre'), ('ml', 'Millilitre'), ('gal', 'Gallon'), ('ft3', 'Cubic Feet'), ('m', 'Meter'), ('cm', 'Centimeter'), ('mm', 'Millimeter'), ('in', 'Inch'), ('ft', 'Foot'), ('m2', 'Square Meter'), ('ft2', 'Square Feet'), ('unit', 'Unit'), ('pcs', 'Piece'), ('set', 'Set'), ('box', 'Box'), ('roll', 'Roll'), ('pack', 'Pack'), ('sheet', 'Sheet'), ('bag', 'Bag'), ('sack', 'Sack'), ('drum', 'Drum'), ('bundle', 'Bundle'), ('pallet', 'Pallet'), ('tube', 'Tube'), ('bottle', 'Bottle'), ('can', 'Can'), ('carton', 'Carton'), ('tray', 'Tray'), ('roller', 'Roller'), ('month', 'Month'), ('ls', 'Lump Sum')], max_length=20)),
                ('subtotal', models.FloatField()),
                ('discount', models.FloatField(default=0.0)),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=20, null=True)),
                ('discount_amount', models.FloatField()),
                ('total', models.FloatField()),
                ('notes', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignatureOnBillOfQuantity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_proof', models.ImageField(upload_to=team.models.upload_signature_proof)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillOfQuantity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('finalized', 'Finalized'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='draft', max_length=20)),
                ('work_weight_total', models.FloatField()),
                ('total', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
