# Generated by Django 5.2.1 on 2025-06-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_billofquantity_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomedetail',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
