# Generated by Django 5.2.1 on 2025-06-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_billofquantityitemdetail_bill_of_quantity_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofquantityitemdetail',
            name='work_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
