# Generated by Django 5.2.1 on 2025-06-18 08:01

import django.db.models.deletion
import django.utils.timezone
import finance.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_documenttype_expensecategory_incomecategory_and_more'),
        ('finance', '0006_alter_billofquantityitemdetail_work_weight'),
        ('project', '0007_rename_deflect_defect_alter_schedule_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofquantitysubitem',
            name='bill_of_quantity_item',
        ),
        migrations.RemoveField(
            model_name='billofquantityitemdetail',
            name='bill_of_quantity_subitem',
        ),
        migrations.RemoveField(
            model_name='billofquantityitemdetail',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='billofquantityitemdetail',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='billofquantityitemdetail',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='billofquantitysubitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='billofquantitysubitem',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='billofquantitysubitem',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='billofquantity',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='billofquantity',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='billofquantity',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='billofquantity',
            name='total',
        ),
        migrations.RemoveField(
            model_name='billofquantity',
            name='work_weight_total',
        ),
        migrations.AddField(
            model_name='billofquantity',
            name='approval_level',
            field=models.CharField(blank=True, choices=[('level_1', 'Level 1'), ('level_2', 'Level 2'), ('level_3', 'Level 3')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='billofquantity',
            name='approval_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='billofquantity',
            name='document_name',
            field=models.CharField(default='Bill of Quantity', max_length=20),
        ),
        migrations.AddField(
            model_name='billofquantity',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Deadline Date'),
        ),
        migrations.AddField(
            model_name='billofquantity',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Upload Date'),
        ),
        migrations.AlterField(
            model_name='billofquantity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_boqs', to='project.project'),
        ),
        migrations.AlterField(
            model_name='expensedetail',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.expensecategory'),
        ),
        migrations.AlterField(
            model_name='expenseformaterial',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.expensecategory'),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.incomecategory'),
        ),
        migrations.CreateModel(
            name='BillOfQuantityVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('finalized', 'Finalized'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='draft', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('total', models.FloatField(blank=True, null=True)),
                ('boq_file', models.FileField(upload_to=finance.models.upload_boq)),
                ('document_number', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_versions', to='finance.billofquantity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BillOfQuantityItem',
        ),
    ]
