# Generated by Django 5.2.1 on 2025-06-18 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_remove_billofquantitysubitem_bill_of_quantity_item_and_more'),
        ('project', '0008_alter_document_document_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillOfQuantityItemDetail',
        ),
        migrations.DeleteModel(
            name='BillOfQuantitySubItem',
        ),
    ]
