# Generated by Django 5.2.1 on 2025-06-19 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_unittype'),
        ('finance', '0009_billofquantityversion_total_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedetail',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unittype'),
        ),
        migrations.AlterField(
            model_name='expenseformaterial',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unittype'),
        ),
        migrations.AlterField(
            model_name='incomedetail',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unittype'),
        ),
    ]
