# Generated by Django 5.2.1 on 2025-06-30 03:07

import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_remove_incomedetail_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to=finance.models.upload_payment_proof),
        ),
    ]
