# Generated by Django 5.2.1 on 2025-05-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initial',
            name='expire_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='expire_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
