# Generated by Django 5.2.1 on 2025-05-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_attendance_leaverequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='statu',
            new_name='status',
        ),
    ]
