# Generated by Django 5.2.1 on 2025-06-04 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_rename_statu_attendance_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('ceo', 'CEO'), ('cto', 'CTO'), ('cfo', 'CFO'), ('qs', 'QS'), ('it', 'IT'), ('spv', 'Supervisor'), ('architect', 'Architect'), ('logistic', 'Logistic'), ('project_admin', 'Project Admin'), ('finance_admin', 'Finance Admin'), ('worker', 'Worker')], max_length=30),
        ),
    ]
