# Generated by Django 5.2.1 on 2025-06-04 07:15

import team.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default_photo/default_profile.jpeg', upload_to=team.models.upload_profile_picture),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('ceo', 'CEO'), ('cto', 'CTO'), ('cfo', 'CFO'), ('qs', 'QS'), ('it', 'IT'), ('spv', 'Supervisor'), ('architect', 'Architect'), ('logistic', 'Logistic'), ('project_admin', 'Project Admin'), ('finance_admin', 'Finance Admin'), ('worker', 'Worker'), ('client', 'Client')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('contract', 'Contract'), ('resign', 'Resign'), ('permanent', 'Permanent'), ('probation', 'Probation'), ('client', 'Client')], max_length=20),
        ),
    ]
