# Generated by Django 5.2.1 on 2025-06-05 02:41

import team.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_alter_profile_profile_picture_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default_photo/default_profile.png', upload_to=team.models.upload_profile_picture),
        ),
    ]
