# Generated by Django 5.2.1 on 2025-06-12 08:52

import django_encrypted_filefield.fields
import team.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initial',
            name='initial',
            field=django_encrypted_filefield.fields.EncryptedImageField(upload_to=team.models.upload_initial),
        ),
    ]
