# Generated by Django 5.2.1 on 2025-06-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_alter_initial_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('contract', 'Contract'), ('resign', 'Resign'), ('permanent', 'Permanent'), ('probation', 'Probation'), ('terminated', 'Terminated'), ('client', 'Client')], max_length=20),
        ),
    ]
