# Generated by Django 5.2.1 on 2025-06-24 02:11

import django.contrib.gis.db.models.fields
import team.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_subcontractorworker_id_photo_signatureonleaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # migrations.AlterField(
        #     model_name='attendance',
        #     name='check_out_location',
        #     field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        # ),
        migrations.AlterField(
            model_name='attendance',
            name='photo_check_out',
            field=models.ImageField(blank=True, null=True, upload_to=team.models.upload_check_out),
        ),
    ]
