# Generated by Django 5.2.1 on 2025-06-24 02:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_alter_attendance_check_out_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='attendance',
        #     name='check_out_location',
        #     field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, spatial_index=False, srid=4326),
        # ),
    ]
