# Generated by Django 5.2.1 on 2025-06-24 02:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_alter_attendance_check_out_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_out_location',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(0 0)', srid=4326),
        ),
    ]
