# Generated by Django 5.2.1 on 2025-06-24 07:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_alter_attendance_check_out_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_out_location',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(115.20762634277344 -8.639009475708008)', srid=4326),
        ),
    ]
