# Generated by Django 5.2.1 on 2025-06-28 05:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0016_alter_attendance_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in_location',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(115.20762634277344 -8.639009475708008)', srid=4326),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
