# Generated by Django 5.2.1 on 2025-10-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0018_remove_profile_update_at_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
