# Generated by Django 5.2.1 on 2026-01-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0020_alter_profile_role_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_location_label',
            field=models.CharField(blank=True, max_length=108, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_location_label',
            field=models.CharField(blank=True, max_length=108, null=True),
        ),
    ]
