# Generated by Django 5.2.1 on 2026-07-28 03:44

import datetime
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import team.models
from django.conf import settings
from django.db import migrations, models


def seed_default_work_policy(apps, schema_editor):
    WorkPolicy = apps.get_model('team', 'WorkPolicy')
    Profile = apps.get_model('team', 'Profile')
    Attendance = apps.get_model('team', 'Attendance')

    policy, _ = WorkPolicy.objects.get_or_create(
        name='Standard',
        defaults={
            'work_start': datetime.time(9, 0),
            'work_end': datetime.time(17, 0),
            'late_grace_minutes': 15,
            'overtime_after_minutes': 30,
            'geofence_radius_meters': 100,
            'workdays': [0, 1, 2, 3, 4],
            'is_active': True,
        },
    )
    Profile.objects.filter(work_policy__isnull=True).update(
        work_policy=policy
    )
    Attendance.objects.filter(work_policy__isnull=True).update(
        work_policy=policy
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_approvalrequest_approvalevent_dataexportjob_and_more'),
        ('team', '0024_team_integrity_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='WorkPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('work_start', models.TimeField(default=datetime.time(9, 0))),
                ('work_end', models.TimeField(default=datetime.time(17, 0))),
                ('late_grace_minutes', models.PositiveIntegerField(default=15)),
                ('overtime_after_minutes', models.PositiveIntegerField(default=30)),
                ('geofence_radius_meters', models.PositiveIntegerField(default=100)),
                ('workdays', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Work policies',
            },
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ('-sent_at',)},
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_minutes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='worked_minutes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='notifications',
            name='action_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='notifications',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('approval', 'Approval'), ('deadline', 'Deadline'), ('inventory', 'Inventory'), ('attendance', 'Attendance'), ('system', 'System')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='notifications',
            name='dedupe_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='photo_check_in',
            field=models.ImageField(blank=True, null=True, upload_to=team.models.upload_check_in),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['user', 'is_read', '-sent_at'], name='team_notification_inbox_idx'),
        ),
        migrations.AddConstraint(
            model_name='notifications',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('user', 'dedupe_key'), name='team_unique_notification_dedupe'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holiday',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holiday',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workpolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workpolicy',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workpolicy',
            name='office_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_policies', to='core.location'),
        ),
        migrations.AddField(
            model_name='workpolicy',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='work_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='team.workpolicy'),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='team.workpolicy'),
        ),
        migrations.RunPython(
            seed_default_work_policy,
            migrations.RunPython.noop,
        ),
    ]
