# Generated by Django 5.2.1 on 2026-07-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0025_holiday_workpolicy_alter_notifications_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status_override',
            field=models.CharField(blank=True, choices=[('Ontime', 'Ontime'), ('Late', 'Late'), ('Early Leave', 'Early Leave'), ('Late & Early Leave', 'Late & Early Leave'), ('Overtime', 'Overtime'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('Holiday', 'Holiday')], help_text='Khusus koreksi superuser. Jika diisi, nilai ini mengesampingkan status hasil perhitungan otomatis.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status_override_reason',
            field=models.TextField(blank=True, help_text='Alasan koreksi status oleh superuser.'),
        ),
    ]
