# Generated by Django 5.2.1 on 2026-09-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0027_attendance_live_location_and_wfh'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('national', 'Kalender Nasional')], default='manual', help_text='Entri "Kalender Nasional" dibuat oleh sinkronisasi otomatis dan boleh ditimpa ulang. Entri manual tidak pernah diubah sync.', max_length=20),
        ),
    ]
