from django.urls import path
from .views import *

urlpatterns = [
    path('boq/', BillOfQuantityModelViewSet.as_view({
        'get': 'list',
        'post': 'create'
    }), name='boq_list'),
    path('boq/<str:pk>/', BillOfQuantityModelViewSet.as_view({
        'get': 'retrieve',
        'put': 'update',
        'delete': 'destroy'
    }), name='boq_detail'),
    path('boq-version/', BillOfQuantityVersionModelViewSet.as_view({
        'get': 'list',
        'post': 'create'
    }), name='boq_version_list'),
    path('boq-version/<str:pk>/', BillOfQuantityVersionModelViewSet.as_view({
        'get': 'retrieve',
        'put': 'update',
        'delete': 'destroy'
    }), name='boq_version_detail'),
    path('boq-signature/', SignatureOnBillOfQuantityModelViewSet.as_view({
        'get': 'list',
        'post': 'create'
    }), name='boq_signature_list'),
    path('boq-signature/<str:pk>/', SignatureOnBillOfQuantityModelViewSet.as_view({
        'get': 'retrieve',
        'put': 'update',
        'delete': 'destroy'
    }), name='boq_signature_detail'),
    path('payment-request/', PaymentRequestModelViewSet.as_view({
        'get': 'list',
        'post': 'create'
    }), name='payment_request_list'),
    path('payment-request/<str:pk>/', PaymentRequestModelViewSet.as_view({
        'get': 'retrieve',
        'put': 'update',
        'delete': 'destroy'
    }), name='payment_request_detail'),
    path('payment-request-version/', PaymentRequestVersionModelViewSet.as_view({
        'get': 'list',
        'post': 'create'
    }), name='payment_request_version_list'),
    path('payment-request-version/<str:pk>/', PaymentRequestVersionModelViewSet.as_view({
        'get': 'retrieve',
        'put': 'update',
        'delete': 'destroy'
    }), name='payment_request_version_detail'),
    path('payment-request-signature/', SignatureOnPaymentRequestModelViewSet.as_view({
        'get': 'list',
        'post': 'create'
    }), name='payment_request_signature_list'),
    path('payment-request-signature/<str:pk>/', SignatureOnPaymentRequestModelViewSet.as_view({
        'get': 'retrieve',
        'put': 'update',
        'delete': 'destroy'
    }), name='payment_request_signature_detail'),
    path('expense/', ExpenseOnProjectModelViewSet.as_view({
        'get': 'list',
        'post': 'create'
    }), name='expense_list'),
    path('expense/<str:pk>/', ExpenseOnProjectModelViewSet.as_view({
        'get': 'retrieve',
        'put': 'update',
        'delete': 'destroy'
    }), name='expense_detail'),
    path('expense-detail/', ExpenseDetailModelViewSet.as_view({
        'get': 'list',
        'post': 'create'
    }), name='expense_detail_list'),
    path('expense-detail/<str:pk>/', ExpenseDetailModelViewSet.as_view({
        'get': 'retrieve',
        'put': 'update',
        'delete': 'destroy'
    }), name='expense_detail_detail'),
    path('expense-material/', ExpenseForMaterialModelViewSet.as_view({
        'get': 'list',
        'post': 'create'
    }), name='expense_material_list'),
    path('expense-material/<str:pk>/', ExpenseForMaterialModelViewSet.as_view({
        'get': 'retrieve',
        'put': 'update',
        'delete': 'destroy'
    }), name='expense_material_detail'),
    path('finance/', FinanceDataModelViewSet.as_view({
        'get': 'list',
        'post': 'create'
    }), name='finance_list'),
    path('finance/<str:pk>/', FinanceDataModelViewSet.as_view({
        'get': 'retrieve',
        'put': 'update',
        'delete': 'destroy'
    }), name='finance_detail'),
    path('petty-cash/', PettyCashModelViewSet.as_view({
        'get': 'list',
        'post': 'create'
    }), name='petty_cash_list'),
    path('petty-cash/<str:pk>/', PettyCashModelViewSet.as_view({
        'get': 'retrieve',
        'put': 'update',
        'delete': 'destroy'
    }), name='petty_cash_detail'),
]