# Generated by Django 5.2.1 on 2025-05-15 03:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialOnProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock', models.FloatField()),
                ('quantity_used', models.FloatField()),
                ('notes', models.TextField()),
                ('approved_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('hand_tool', 'Hand Tool'), ('power_tool', 'Power Tool'), ('measuring', 'Measuring'), ('safety', 'Safety'), ('heavy_equipment', 'Heavy Equipment'), ('cutting', 'Cutting'), ('lifting', 'Lifting'), ('demolition', 'Demolition'), ('other', 'Other')], max_length=20)),
                ('serial_number', models.CharField(max_length=255)),
                ('conditions', models.TextField()),
                ('amount', models.IntegerField()),
                ('avalable', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolOnProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('assigned_date', models.DateField()),
                ('returned_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('structural', 'Structural'), ('finishing', 'Finishing'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('hardware', 'Hardware'), ('chemical', 'Chemical'), ('interior', 'Interior'), ('exterior', 'Exterior'), ('other', 'Other')], max_length=255)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('ton', 'Ton'), ('lb', 'Pound'), ('m3', 'Cubic Meter'), ('l', 'Litre'), ('ml', 'Millilitre'), ('gal', 'Gallon'), ('ft3', 'Cubic Feet'), ('m', 'Meter'), ('cm', 'Centimeter'), ('mm', 'Millimeter'), ('in', 'Inch'), ('ft', 'Foot'), ('m2', 'Square Meter'), ('ft2', 'Square Feet'), ('unit', 'Unit'), ('pcs', 'Piece'), ('set', 'Set'), ('box', 'Box'), ('roll', 'Roll'), ('pack', 'Pack'), ('sheet', 'Sheet'), ('bag', 'Bag'), ('sack', 'Sack'), ('drum', 'Drum'), ('bundle', 'Bundle'), ('pallet', 'Pallet'), ('tube', 'Tube'), ('bottle', 'Bottle'), ('can', 'Can'), ('carton', 'Carton'), ('tray', 'Tray'), ('roller', 'Roller'), ('month', 'Month'), ('ls', 'Lump Sum')], max_length=20)),
                ('standart_price', models.FloatField()),
                ('descriptions', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
