# Generated by Django 5.2.1 on 2025-05-21 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='avalable',
            new_name='available',
        ),
    ]
