# Generated by Django 5.2.1 on 2025-06-10 04:09

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_avalable_tool_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialonproject',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.upload_materials),
        ),
        migrations.AddField(
            model_name='tool',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.upload_tools),
        ),
    ]
