# Generated by Django 5.2.1 on 2025-06-18 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_documenttype_expensecategory_incomecategory_and_more'),
        ('inventory', '0004_materialonproject_photo_tool_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.materialcategory'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.toolcategory'),
        ),
    ]
