# Generated by Django 5.2.1 on 2025-06-19 03:29

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_material_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.upload_materials),
        ),
        migrations.AlterField(
            model_name='materialonproject',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.upload_materials_project),
        ),
    ]
