# Generated by Django 5.2.1 on 2025-06-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_material_photo_alter_materialonproject_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
