# Generated by Django 5.2.1 on 2025-10-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_material_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialonproject',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
