# Generated by Django 5.2.1 on 2025-10-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_materialonproject_approved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolonproject',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
