# Generated by Django 5.2.1 on 2025-05-21 03:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyreport',
            old_name='Progress_percentage',
            new_name='progress_percentage',
        ),
        migrations.AlterField(
            model_name='errorlogdetail',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
