# Generated by Django 5.2.1 on 2025-06-03 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_progress_percentage_weeklyreport_progress_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='DueDate',
            new_name='due_date',
        ),
    ]
