# Generated by Django 5.2.1 on 2025-06-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='mime_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
