# Generated by Django 5.2.1 on 2025-06-10 04:09

import project.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_documentversion_mime_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deflect',
            new_name='Defect',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='attachment',
            field=models.FileField(upload_to=project.models.upload_schedule_attachment),
        ),
        migrations.AlterField(
            model_name='workmethod',
            name='photo',
            field=models.FileField(upload_to=project.models.upload_work_method_photo),
        ),
    ]
