# Generated by Django 5.2.1 on 2025-06-18 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_documenttype_expensecategory_incomecategory_and_more'),
        ('finance', '0007_remove_billofquantitysubitem_bill_of_quantity_item_and_more'),
        ('project', '0007_rename_deflect_defect_alter_schedule_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.documenttype'),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.worktype'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='boq_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules_boq', to='finance.billofquantity'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='boq_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_boq', to='finance.billofquantity'),
        ),
    ]
