# Generated by Django 5.2.1 on 2025-06-19 03:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_document_document_type_and_more'),
        ('team', '0010_alter_profile_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentversion',
            name='mime_type',
        ),
        migrations.AddField(
            model_name='documentversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('finalized', 'Finalized'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='DefectDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_detail', models.CharField(max_length=255)),
                ('deviation', models.CharField(max_length=255)),
                ('initial_checklist_date', models.DateTimeField()),
                ('final_checklist_date', models.DateTimeField()),
                ('notes', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('deflect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deflect_detail', to='project.defect')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('final_checklist_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approval', to='team.initial')),
                ('initial_checklist_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_approval', to='team.initial')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='DeflectDetail',
        ),
    ]
