# Generated by Django 5.2.1 on 2025-06-28 05:09

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_rename_photo_workmethod_file_defectdetail_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreport',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=project.models.upload_weekly_report_attachment),
        ),
    ]
