# Generated by Django 5.2.1 on 2025-10-13 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_progressreport_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_defect', to='project.project'),
        ),
        migrations.AlterField(
            model_name='defectdetail',
            name='deflect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_detail', to='project.defect'),
        ),
        migrations.AlterField(
            model_name='errorlogdetail',
            name='error',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_detail', to='project.errorlog'),
        ),
        migrations.AlterField(
            model_name='signatureondeflect',
            name='deflect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_signature', to='project.defect'),
        ),
        migrations.AlterField(
            model_name='workmethod',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_method_project', to='project.project'),
        ),
    ]
