# Generated by Django 5.2.1 on 2025-10-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_defect_project_alter_defectdetail_deflect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='periode_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
