# Generated by Django 5.2.1 on 2026-07-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_project_indexes_and_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5),
        ),
    ]
